services:
  - type: web
    name: api-embrapa-offline
    env: docker
    plan: free
    dockerfilePath: Tech_challenge/offline/Dockerfile
    autoDeploy: true

services:
  - type: web
    name: api-embrapa-offline
    env: docker
    plan: free
    dockerfilePath: Tech_challenge/online/Dockerfile
    autoDeploy: true
